# Generated by Django 2.0.7 on 2018-07-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=500)),
                ('ratings', models.IntegerField(default=0)),
                ('insertime', models.DateTimeField(verbose_name='insertime')),
            ],
        ),
    ]
