# Generated by Django 2.0.7 on 2018-07-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='insertime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
